<a href="https://colab.research.google.com/github/Tulasi-ummadipolu/Data-science-Batch1/blob/main/Data%20science%20Assignment-1%20Day-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question No-1

In [8]:
import numpy as np

arr=np.arange(2,50,3)

print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Quesyion No-2

In [9]:
import numpy as np

list1=[]
list2=[]
print("Enter list1 Elements:")
for i in range(5):
    x=int(input())
    list1.append(x)

print("Enter list2 Elements:")
for i in range(5):
    x=int(input())
    list2.append(x)

arr1=np.array(list1)
arr2=np.array(list2)

print("Concatenate array:")
arr3=np.concatenate((arr1,arr2))
print(arr3)

print("Sorted array:")
arr4=np.sort(arr3)
print(arr4)

Enter list1 Elements:
9
8
7
6
5
Enter list2 Elements:
0
1
2
3
4
Concatenate array:
[9 8 7 6 5 0 1 2 3 4]
Sorted array:
[0 1 2 3 4 5 6 7 8 9]


Question No-3

In [10]:
import numpy as np
arr=np.array([[2,3,4],[4,5,6],[7,8,9]])

print("Dimentions of ndrray:",arr.ndim)

print("Size of the Array:",arr.size)

Dimentions of ndrray: 2
Size of the Array: 9


Question No-4
1.Newaxis Snippet

In [11]:
import numpy as np

arr=np.arange(8)
print("Shape of the array:",arr.shape)

row_arr=arr[np.newaxis, :]
print("Shape of 2d array ROW Major:",row_arr.shape)

colm_arr=arr[: ,np.newaxis]
print("Shape of 2d array Column Major:",colm_arr.shape)

Shape of the array: (8,)
Shape of 2d array ROW Major: (1, 8)
Shape of 2d array Column Major: (8, 1)


2.Expand Snippet

In [12]:
import numpy as np

arr=np.arange(8)
print("Shape of the array:",arr.shape)

row_arr=np.expand_dims(arr,axis=0)
print("Shape of 2d array ROW Major:",row_arr.shape)

colm_arr=np.expand_dims(arr,axis=1)
print("Shape of 2d array Column Major:",colm_arr.shape)

Shape of the array: (8,)
Shape of 2d array ROW Major: (1, 8)
Shape of 2d array Column Major: (8, 1)


Question No-5

In [13]:
import numpy as np

arr1=np.square([1,2,3,4,5])
arr2=np.square([10,9,8,7,6])

print("Stack Horizontal:",np.hstack((arr1,arr2)))
print("Stack Vertical:",np.vstack((arr1,arr2)))

Stack Horizontal: [  1   4   9  16  25 100  81  64  49  36]
Stack Vertical: [[  1   4   9  16  25]
 [100  81  64  49  36]]


Question No-6

In [14]:
import numpy as np

arr1=np.array([1,2,3,5,3,4,6,7,3,8,6,5,9,8,2,9,1,25,56,84])

unique, counts=np.unique(arr1,return_counts=True)

arr2=np.asarray((unique,counts)).T
print(arr2)

[[ 1  2]
 [ 2  2]
 [ 3  3]
 [ 4  1]
 [ 5  2]
 [ 6  2]
 [ 7  1]
 [ 8  2]
 [ 9  2]
 [25  1]
 [56  1]
 [84  1]]
